# Generated by Django 5.1.2 on 2024-11-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0003_remove_appointment_status_appointment_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='ppointment_date',
            new_name='apointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='ppointment_time',
            new_name='apointment_time',
        ),
    ]
